import tempfile

import pytest
from tortoise import Tortoise


@pytest.fixture(autouse=True)
async def init_db(tmp_path):
    """Override the root init_db to use a file-based SQLite database.

    Starlette's TestClient runs the ASGI app in a separate thread, which
    causes Tortoise to reconnect on a new event loop.  A plain
    ``sqlite://:memory:`` creates a *new* database per connection, so the
    schemas generated by the fixture are lost.  A file-based database
    survives the reconnection.
    """
    db_path = tmp_path / "test.db"
    await Tortoise.init(
        db_url=f"sqlite://{db_path}",
        modules={
            "models": [
                "tests.models",
                "tortoise_auth.models.jwt_blacklist",
            ]
        },
    )
    await Tortoise.generate_schemas()
    yield
    await Tortoise.close_connections()