import os
import threading

import pytest_asyncio
from tortoise import Tortoise
from tortoise.context import tortoise_test_context

_exit_code = 0


@pytest_asyncio.fixture(scope="function", autouse=True)
async def init_db(tmp_path):
    """Override the root init_db to use a file-based SQLite database.

    Starlette's TestClient runs the ASGI app in a separate thread, which
    causes Tortoise to reconnect on a new event loop.  A plain
    ``sqlite://:memory:`` creates a *new* database per connection, so the
    schemas generated by the fixture are lost.  A file-based database
    survives the reconnection.
    """
    db_path = tmp_path / "test.db"
    async with tortoise_test_context(
        modules=[
            "tests.models",
            "tortoise_auth.models.jwt_blacklist",
        ],
        db_url=f"sqlite://{db_path}",
    ) as ctx:
        yield ctx
    await Tortoise.close_connections()


def pytest_sessionfinish(session, exitstatus):
    global _exit_code
    _exit_code = exitstatus


def pytest_unconfigure(config):
    """Force-exit if orphaned aiosqlite threads prevent clean shutdown.

    Starlette's TestClient triggers Tortoise reconnection across event loops,
    leaving non-daemon aiosqlite worker threads that can't be cleanly closed.
    See: https://github.com/pytest-dev/pytest/issues/7250
    """
    stale = [
        t
        for t in threading.enumerate()
        if t is not threading.main_thread() and not t.daemon and t.is_alive()
    ]
    if stale:
        os._exit(_exit_code)
