"""Async authentication and user management for Tortoise ORM."""

__version__ = "0.5.0"

from tortoise_auth.config import AuthConfig, configure, get_config
from tortoise_auth.events import emit, emitter, on
from tortoise_auth.exceptions import (
    AuthenticationError,
    BadSignatureError,
    ConfigurationError,
    EventError,
    InvitationAlreadyAcceptedError,
    InvitationError,
    InvitationExpiredError,
    InvitationNotFoundError,
    InvitationRevokedError,
    InvalidHashError,
    InvalidPasswordError,
    OnboardingError,
    OnboardingFlowCompleteError,
    OnboardingSessionExpiredError,
    OnboardingSessionInvalidError,
    OnboardingStepError,
    PasskeyAuthenticationError,
    PasskeyError,
    PasskeyRegistrationError,
    PasswordResetError,
    RateLimitError,
    SignatureExpiredError,
    SigningError,
    TokenError,
    TokenExpiredError,
    TokenInvalidError,
    TokenRevokedError,
    TortoiseAuthError,
)
from tortoise_auth.models import (
    AbstractUser,
    AccessToken,
    BlacklistedToken,
    Invitation,
    LoginAttempt,
    OnboardingSession,
    OutstandingToken,
    PasskeyCredential,
    RefreshToken,
    WebAuthnChallenge,
)
from tortoise_auth.onboarding import (
    ClientHint,
    FieldHint,
    OnboardingResult,
    OnboardingStep,
    OnboardingStepStatus,
    StepContext,
    StepResult,
)
from tortoise_auth.onboarding.flow import OnboardingFlow
from tortoise_auth.onboarding.service import OnboardingService
from tortoise_auth.onboarding.steps import (
    ProfileCompletionStep,
    RegisterPasskeyStep,
    RegisterStep,
    SetupTOTPStep,
    ValidateInvitationStep,
    VerifyEmailStep,
)
from tortoise_auth.passkey import ChallengeBackend, ChallengeData, PasskeyService
from tortoise_auth.passkey.challenge_database import DatabaseChallengeBackend
from tortoise_auth.passkey.challenge_memory import InMemoryChallengeBackend
from tortoise_auth.rate_limit import RateLimitBackend, RateLimitResult
from tortoise_auth.rate_limit.database import DatabaseRateLimitBackend
from tortoise_auth.rate_limit.memory import InMemoryRateLimitBackend
from tortoise_auth.services import (
    AuthService,
    InvitationService,
    PasswordResetService,
    S2SAuthResult,
    S2SService,
)
from tortoise_auth.signing import Signer, TimestampSigner, make_token, verify_token
from tortoise_auth.tokens import AuthResult, TokenBackend, TokenPair, TokenPayload
from tortoise_auth.tokens.database import DatabaseTokenBackend
from tortoise_auth.tokens.jwt import JWTBackend

__all__ = [
    "AbstractUser",
    "AccessToken",
    "AuthConfig",
    "AuthResult",
    "AuthService",
    "AuthenticationError",
    "BadSignatureError",
    "BlacklistedToken",
    "ChallengeBackend",
    "ChallengeData",
    "ClientHint",
    "ConfigurationError",
    "DatabaseChallengeBackend",
    "DatabaseRateLimitBackend",
    "DatabaseTokenBackend",
    "EventError",
    "FieldHint",
    "InMemoryChallengeBackend",
    "Invitation",
    "InvitationAlreadyAcceptedError",
    "InvitationError",
    "InvitationExpiredError",
    "InvitationNotFoundError",
    "InvitationRevokedError",
    "InvitationService",
    "InMemoryRateLimitBackend",
    "InvalidHashError",
    "InvalidPasswordError",
    "JWTBackend",
    "LoginAttempt",
    "OnboardingError",
    "OnboardingFlow",
    "OnboardingFlowCompleteError",
    "OnboardingResult",
    "OnboardingService",
    "OnboardingSession",
    "OnboardingSessionExpiredError",
    "OnboardingSessionInvalidError",
    "OnboardingStep",
    "OnboardingStepError",
    "OnboardingStepStatus",
    "OutstandingToken",
    "PasskeyAuthenticationError",
    "PasskeyCredential",
    "PasskeyError",
    "PasskeyRegistrationError",
    "PasskeyService",
    "PasswordResetError",
    "PasswordResetService",
    "ProfileCompletionStep",
    "RateLimitBackend",
    "RateLimitError",
    "RateLimitResult",
    "RefreshToken",
    "RegisterPasskeyStep",
    "RegisterStep",
    "S2SAuthResult",
    "S2SService",
    "SetupTOTPStep",
    "SignatureExpiredError",
    "Signer",
    "SigningError",
    "StepContext",
    "StepResult",
    "TimestampSigner",
    "TokenBackend",
    "TokenError",
    "TokenExpiredError",
    "TokenInvalidError",
    "TokenPair",
    "TokenPayload",
    "TokenRevokedError",
    "TortoiseAuthError",
    "ValidateInvitationStep",
    "VerifyEmailStep",
    "WebAuthnChallenge",
    "configure",
    "emit",
    "emitter",
    "get_config",
    "make_token",
    "on",
    "verify_token",
]
