name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    name: Build & publish
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1